# Generated by Django 5.0.1 on 2024-02-05 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_jobBoard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobListing',
            new_name='Job',
        ),
    ]
