# Generated by Django 5.0.1 on 2024-02-06 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_jobBoard', '0002_rename_joblisting_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('emailAddress', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=100)),
            ],
        ),
    ]
