# Generated by Django 5.0.1 on 2024-02-06 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_jobBoard', '0003_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
